### ISSUE TITLE
Automatic management of kasFloodDelay

### ISSUE THREAD

**Issue by rhurling** [waza-ari/kasapi-php#10]
Would something like automatic management of the kasFloodDelay be interesting?
I'm currently using a connector class like this:
```php
class KasApiConnector extends \KasApi\KasApi {

	private $next_call_time = 0;

	protected function call( $function, $params = array() ) {
		$now = time();
		if ($now < $this->next_call_time) {
			sleep($this->next_call_time - $now);
		}
		$return = parent::call( $function, $params );
		$this->next_call_time = time() + (int)$this->kasFloodDelay;
		return $return;
	}
}
```

It's very useful if I'm using the API in a CLI script to change things for a lot of Domains in one Account at once (Upgrading all PHP Versions, etc).

**Comment by waza-ari** [comment]
Hi,

thank you again for your contribution. I could imagine this to be useful, if you want to ensure that your call is definitely executed. On the other hand it is blocking and would add waiting time. In case the API is called directly during a user call, this would add delay.

Maybe it should be configurable? If the automatic management is enabled, something like your code could be used to manage this automatically. I'd like to give the developers the freedom to choose not to add an automatic management system using sleeps. If disabled, an exception could be thrown which then must be handled by the developer.
