### ISSUE TITLE
Wrong labeled release v0.51

### ISSUE THREAD

**Issue by rhurling** [waza-ari/kasapi-php#12]
If someone uses `composer require wazaari/kasapi-php` to get the package and/or uses `"minimum-stability": "stable"` they won't get the latest release of the package.

Could you fix that by either retagging it in git and remove the wrong version in packagist?
Or just tagging a newer version as `0.52` with a note.

I for one don't really want to use a `dev-master` package (if some type of release tagging is available).

**Comment by waza-ari** [comment]
Hm, don't know how this release went unnoticed for the last years... It might be a little rude for those relying on this release, but I did not see a clean way to fix it.

I deleted both the release and the tag which as labeled wrong. Thanks for letting me know.

**Comment by rhurling** [comment]
I think you need to delete the release on [packagist](https://packagist.org/packages/wazaari/kasapi-php) as well. You should be able to delete them in the version list when you're logged in.
